### ISSUE TITLE
npm start/ npm run deploy issue

### ISSUE THREAD

**Issue by StephenEller86** [spences10/twitter-bot-twit#98]
Changed to node 8.
installed console.lol, now, dotenv, twit, unique-random-array, snyk.
added "deploy": "now -E" under scripts in package.json.

ec2-user:~/environment/twitter-bot-twit (master) $ npm start

twitter-bot-twit@0.0.1 start /home/ec2-user/environment/twitter-bot-twit
node index.js

at this point nothing happens....

my env file:

```sh
TWITTER_CONSUMER_KEY=******************
TWITTER_CONSUMER_SECRET=********************
TWITTER_ACCESS_TOKEN=*******************
TWITTER_ACCESS_TOKEN_SECRET= ***************

QUERY_STRING=[1,2,3,4,5]

RESULT_TYPE=mixed
LANGUAGE=en
TWITTER_USERNAME=username

RANDOM_REPLY=Hi @${screenName} thanks for the follow!|@${screenName} thanks for following! 
RANDOM_EMOJI=['', '', '','️','','']

TWITTER_RETWEET_RATE=.1
TWITTER_SEARCH_COUNT=20

TWITTER_USERNAME_BLACKLIST=[
name,
name1,
name2
]
```

Do you have any idea why this stops at this point? 

Separately, If I deploy, it deploys fine, and zeit lists it with no errors, but it doesn't do anything.

**Comment by spences10** [comment]
Hey @toxxn  thanks for taking an interest in my bot, again I haven't really checked in with this code for a while so I can't really give you any guidance other than to maybe take a look at [the Twitter bot playground] repo I put together a while back that goes from a simple hello world tweet right up to posting media.

Oh, looking at the config you have there `.env` files don't understand arrays so you'll need to have your blacklist in a delimited list (i.e. comma, pipe separated) no square brackets all on the same line 👌

```sh
TWITTER_USERNAME_BLACKLIST=name,name1,name2
```
Have fun 👌👍

[the Twitter bot playground]: https://github.com/spences10/twitter-bot-playground

**Comment by spences10** [comment]
Closing this for now, let me know if there's anything else needed @toxxn 👍
